services:
  client:
    build: ./client
    container_name: lotus-client
    restart: unless-stopped
    ports:
      - "3165:3000"
    env_file:
      - ./client/.env
    depends_on:
      - server
    networks:
      - lotus_net

  lotus-redis:
    image: redis:7-alpine
    container_name: lotus-redis
    restart: unless-stopped
    ports:
      - "6383:6379"
    networks:
      - lotus_net

  server:
    build: ./server
    container_name: lotus-server
    restart: unless-stopped
    ports:
      - "5497:8080"
    env_file:
      - ./server/.env
    depends_on:
      - lotus-redis
    networks:
      - lotus_net

  smtp-service-lotus:
    image: maildev/maildev
    container_name: smtp-service-lotus
    restart: unless-stopped
    environment:
      - NODE_OPTIONS=--no-warnings=DeprecationWarning
      - DEBUG=maildev*
    env_file:
      - ./server/.env
    command:
      --outgoing-host smtp.gmail.com
      --outgoing-port 465
      --outgoing-secure
      --outgoing-user mailer7012@gmail.com
      --outgoing-pass "ldxm ypzz ewvf mnwq"
      --auto-relay
      --verbose
    ports:
      - "8185:1080"
    networks:
      - lotus_net

networks:
  lotus_net:
    driver: bridge
